version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ecookbook
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
    - datadb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - proxynet
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - proxynet
  rabbit:
    image: rabbitmq
    restart: always
    hostname: "ecookbook"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
    - 5672:5672
    - 15672:15672
    networks:
      - proxynet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
    - dataes:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
      - proxynet
  celery:
    build: .
    command: celery -A ecookbook worker -l info
    restart: always
    volumes:
    - .:/code
    depends_on:
      - db
      - rabbit
      - elasticsearch
      - redis
    networks:
      - proxynet
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
    - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbit
      - elasticsearch
      - redis
      - celery
    networks:
      - proxynet

volumes:
  datadb:
  dataes:
networks:
  proxynet: