# Generated by Django 3.1.4 on 2020-12-12 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recipes.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='calories')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='protein')),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='carbohydrates')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='carbohydrates')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='amount')),
                ('unit', models.CharField(max_length=64, verbose_name='unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=recipes.utils.recipe_image_upload_to, verbose_name='recipe image')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to=recipes.utils.step_image_upload_to, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('publication_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication time')),
                ('cooking_time', models.DurationField(verbose_name='cooking time')),
                ('servings', models.SmallIntegerField(verbose_name='number of servings')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.chef')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipeimage')),
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.nutrition')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.product')),
                ('steps', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.step')),
            ],
        ),
        migrations.AddField(
            model_name='chef',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='chef',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='chef',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
