# Generated by Django 3.1.4 on 2020-12-12 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201212_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='carbohydrates'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='carbohydrates'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='amount'),
        ),
    ]
