# Generated by Django 3.1.4 on 2020-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201212_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('Volume', (('TSP', 'teaspoon'), ('TBL', 'tablespoon'), ('OZ', 'fluid ounce'), ('C', 'cup'), ('PT', 'pint'), ('QT', 'quart'), ('GAL', 'gallon'), ('ML', 'milliliter'), ('L', 'liter'))), ('Mass and Weight', (('LB', 'pound'), ('OZ', 'ounce'), ('G', 'gram'), ('KG', 'kilogram'))), ('Length', (('MM', 'millimeter'), ('CM', 'centimeter'), ('M', 'meter'), ('IN', 'inch'))), ('PI', 'piece')], max_length=64, verbose_name='unit'),
        ),
    ]
